# Generated by Django 3.1.7 on 2021-05-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_scan_domain_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('scan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.scan')),
            ],
        ),
    ]
