# Generated by Django 3.1.7 on 2021-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_resultfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_bookmark',
            field=models.IntegerField(default=0),
        ),
    ]
