# Generated by Django 3.1.7 on 2021-07-26 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_scan_is_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='domain_url',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='([a-z0-9]{2,}\\.)+[a-z0-9]{2,5}')]),
        ),
    ]
